feat: improve body parsing logic
stefanbuck/github-issue-parser pull request #72
Opened 2024-04-26 17:03 UTC by Ansuel

Current body parsing logic with trim() + split("###") is too fragile and
pose problems with some body that contains case with ### in the middle
of the line or case with codeblock ``` section.

These case will cause the script to parse these as separate section and
produce wrong outputs and in some case even prints error assuming things
are checkbox and errors out on the concat function.

To make the parsing logic more solid, implement a dedicated function and
parse with this logic:
- We split the body for "\n"
- We ignore codeblock ``` section
- We check "###" only at the start of the line
- We check for "### " (with the space included) as that is the correct
  section Github issue template expects.

With the following change case like:
```
root@OpenWrt:~# cat /boot/config.txt
```

Are correctly parsed as all part of a single section instead of being
wrongly treated as different empty sections.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

2024-04-26 17:06 UTC, Ansuel commented
Discovered by this https://github.com/openwrt/openwrt/issues/15265

Made further research and found the root of the problem!

2024-04-29 07:05 UTC, jamacku requested changes

2024-04-29 07:05 UTC, jamacku commented on index.js
> +      if (line == "```")
Please also account for instances when the context of the code block is specified. For example:

```
```md
```

2025-01-31 12:38 UTC, Ansuel commented on index.js
> +      if (line == "```")
Funnily enough I just encounter this bug and was ready to report this problem just only to discover I was the culprit LOL...

my bad...

2025-01-31 12:56 UTC, Ansuel commented
@jamacku sorry for the delay... I fixed the comment and also add an additional test to catch this special case. We check now if line start with ``` directly.

2025-01-31 13:16 UTC, jamacku approved these changes
LGTM, Thank you.

2025-02-05 23:20 UTC, stefanbuck commented
Awesome, good stuff. I will have a closer look shortly and then cut a new major version for this change.

2026-04-22 14:59 UTC, gr2m commented
Gonna merge as fix. No breaking changes are introduced. Thanks @Ansuel!

2026-04-22 15:00 UTC, merged

2026-04-22 15:02 UTC, Ansuel commented
@gr2m thanks a lot!